<!-- TODO: Update informed consent!! -->
<x-app-layout>
    <x-slot name="slot">
        <div class="min-h-screen bg-gray-200 flex justify-center items-center">
            <div class="p-12 m-10 bg-white rounded-2xl shadow-xl z-20">
                <div class="text-left font-bold my-3 max-w-4xl text-3xl w-full">
                    INFORMED CONSENT FORM
                    FOR PARTICIPATING TO THE RESEARCH STUDY
                    <p class="mt-6 text-lg font-medium max-w-4xl">
                        Dear Sir/Madam,<br>
                        You are invited to participate in the research study “Customised training campaigns for defence against cyber attacks and Creation of digital twin for simulating cyber attacks”.
                        <br>
                        To ensure informed participation, we are providing you with information regarding the nature of the study, the objectives of the project, and the activities in which you may be involved to achieve the research goals.
                        <br>
                        Please read this information carefully before making a decision about your possible participation in the project. You may ask any clarifying questions and raise any concerns if you have not received a clear and satisfactory response.
                        <br>
                        If, after reading and understanding all the provided information, you decide to participate in the study, you will be asked to accept the Informed Consent Form presented hereafter.
                        <br>
                        We will not collect any personal information during the study. We will only ask you to provide your first name for personalisation purposes, which will not allow us to identify you.
                    </p>

                    <!--<div class="font-medium text-lg mt-6">
                    YOU CAN DOWNLOAD A COPY OF THIS INFORMATION SHEET BY <a class="font-bold underline"
                            href="{{route("download_information_sheet")}}" style="color:dodgerblue" target="_blank">CLICKING HERE</a>
                    </div>-->
                </div>
                <p class="text-xl max-w-4xl text-left pt-4 font-bold capitalize">
                    INFORMATION RELATED TO PARTICIPATION IN THE RESEARCH
                </p>
                <div class="text-xl max-w-4xl text-left pt-4 mt-8">
                    <ul>
                        <li>
                            <b>Research Title:</b> <i>“Customised training campaigns for defence against cyber attacks and Creation of digital twin for simulating cyber attacks”</i>.
                        </li>
                        <li>
                            <b>Project CUP:</b> H53D23008140001
                        </li>
                        <li>
                            <b>Sponsor:</b> European PRIN PNRR 2022 “DAMOCLES” (Detection And Mitigation Of Cyber attacks that exploit human vuLnerabilitiES)
                        </li>
                        <li>
                            <b>Involved Entities:</b> University of Bari “A. Moro”, University of Cagliari, King’s College London
                        </li>
                    </ul>
                </div>
            <div class="text-lg pt-3 font-bold italic mt-8" style="color:darkred"> GOALS </div>
                <p class="text-xl max-w-4xl text-left pt-4">
                    This study has two primary objectives.
                    The first is to evaluate the effectiveness of training modules designed to help users defend against phishing attacks.
                    These modules will be automatically generated by a Large Language Model—an Artificial Intelligence tool capable of creating customised training materials based on individual user profiles.
                    These profiles are developed through questionnaires, which help the AI tailor the training for greater relevance and effectiveness.
                    <br><br>
                    The second objective is to create a “digital twin” of the user—a virtual model that mimics their behavior.
                    Digital twins can be highly valuable for cybersecurity assessments, allowing researchers to conduct realistic simulations without exposing individuals to actual risks.
                </p>

                <div class="text-lg pt-3 font-bold italic mt-8" style="color:darkred"> STUDY DESCRIPTION
                </div>
                <p class="text-xl max-w-4xl text-left pt-4">
                    The participation to the study takes <b>about {{\Illuminate\Support\Facades\Auth::user()?->training_length == "short" ? 20 : 25}} minutes</b> and will have 4 main phases:
                    <ol class="text-xl max-w-4xl text-left pt-4" style="list-style-type: decimal; list-style-position: inside">
                        <li>
                            <b>Profiling questionnaires (&#126;7 min):</b> Participants will complete a demographic questionnaire and three standardised questionnaires (BFI-2 XS, StP-II B, TEIQue-SF) to assess personality traits, susceptibility to persuasion, and emotional intelligence. No personal or sensitive data will be collected.
                        </li>
                        <li>
                            <b>Pre-training assessment (&#126;3 min):</b> Participants will evaluate 12 static emails (a mix of phishing and genuine) and indicate whether each is “phishing” or “non-phishing.”.
                        </li>
                        <li>
                            <b>Training (&#126;{{\Illuminate\Support\Facades\Auth::user()?->training_length == "short" ? 8 : 15}} min):</b> Participants will receive AI-customised training on phishing attacks, tailored to their profile based on questionnaire responses.
                        </li>
                        <li>
                            <b>Post-training assessment (&#126;3 min):</b> Participants will evaluate 12 more emails to measure changes in phishing detection accuracy.
                        </li>
                    </ol>
                </p>

                <div class="text-lg pt-3 font-bold italic mt-8" style="color:darkred"> BENEFITS </div>
                <p class="text-xl max-w-4xl text-left pt-4">
                    Participants who will take part in this study will learn concepts and skills about defense from phishing emails. <br>
                    Moreover, a reward of <u>9£ per hour</u> will be granted via participation on Prolific.
                </p>

                <div class="text-lg pt-3 font-bold italic mt-8"" style="color:darkred"> RISKS </div>
                <p class="text-xl max-w-4xl text-left pt-4">
                    No potential risk for the participants is expected throughout the study.
                    <br>
                    The researchers will only have access to the user’s Prolific ID, and have no way of retrieving any identifying information from such identifier.
                </p>

                <div class="text-lg mt-8 max-w-4xl font-medium">Thank you for reading this information sheet and
                    for considering taking part in this research.
                    <br>To proceed to the study, please read carefully the following statements and express
                    your consent by pressing the <b>"AGREE"</b> button at the bottom of this page.
                </div>

                <div class="text-lg mt-8 pt-3 font-bold italic">INFORMATION CONSENT FOR PARTICIPANTS</div>
                <div class="text-xl max-w-4xl text-left pt-4">
                    <p>
                        Please give your consent only after you have read the Information Sheet.
                        <br>
                        I declare that:
                    </p>
                    <ol class="list-disc" style="margin: revert; padding: revert;">
                        <li>
                            I have voluntarily decided to participate in the research;
                        </li>
                        <li>
                            I have received all necessary information regarding the request to participate in the research, particularly regarding its purpose, procedures, and what is required of me;
                        </li>
                        <li>
                            I have received, read, and understood the document titled “Information on Research Participation,” which has been provided to me, and I have obtained all necessary information for responsible participation in the research;
                        </li>
                        <li>
                            I have had the opportunity to ask questions and have received clear, complete, and satisfactory answers;
                        </li>
                        <li>
                            I have been informed of any possible risks;
                        </li>
                        <li>
                            I am aware that my participation is voluntary;
                        </li>
                        <li>
                            I have been assured that I can withdraw from the research at any time without any negative consequences on my treatment or care.
                        </li>
                    </ol>
                    <p>
                        For any doubt or question, you can contact <b>Prof. Giuseppe Desolda</b>
                        <div class="mt-4"> - Email: <a href="mailto:giuseppe.desolda@uniba.it" style="color:dodgerblue"> giuseppe.desolda@uniba.it </a></div>
                        <div class=""> - Phone: <a href="tel:+39-0805443289" style="color:dodgerblue"> +39-0805443289 </a> </div>
                    </p>

                    <p class="mt-8">
                        First and last name of the subject who acquired the consent: <i>Giuseppe Desolda</i>
                    </p>
                    <p>
                        Date: {{date("d/m/Y")}}
                    </p>
                </div>

                <div class="text-center mt-10">
                    <div class="w-full">
                        <div class="flex flex-row">
                            <button style="margin: 0 1rem;"
                                onclick="window.location.replace('{{ route('no_consent') }}')"
                                class="py-3 w-1/2 text-lg text-white bg-blue-500 hover:bg-blue-800 rounded-2xl">
                                DISAGREE
                            </button>
                            <button style="margin: 0 1rem;" onclick="window.location.replace('{{ route('consent') }}')"
                                class="py-3 w-1/2 text-lg text-white bg-blue-500 hover:bg-blue-800 rounded-2xl"> AGREE
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </x-slot>
</x-app-layout>
